# Changes here will be overwritten by Copier
_commit: v0.1.2
_src_path: gh:igembitsgoa/igem-wiki-starter
author: tamithia
email: astrallynja@gmail.com
iGEM_official_team_name: Stockholm
iGEM_team_name: Stockholm
year: 2020